language: node_js
node_js: node
addons:
  chrome: stable
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:polymer:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:polymer:local || travis_terminate 1;
  fi
env:
  global:
  - SAUCE_USERNAME: Desire2Learn
  - secure: QRLmxddvVuYWH4biWw+rh8hNV16byq4FLPvLG+rL/M6Y7Peb1Gi8351ZWWW19GQVjq9T+Hs0WJjjC8pmvx0Bksfc6shitvgVvl184yLfFARRvJ37KIIYBhAqL9H26BYONzOGazYaKVcihjg+9zRbZ9w7PSimTgU/SxIX4ju/TpmnZasTwsp6e58+ELwrE30wvOW0o8+STgLZXA/wM00nhfj/oIEKRDFrZP+9BKuA/qBGHIdCubxpMn20FrMhB6JrLackvLH9jmrThtWdrsacgCT9XtUoQqbCTYthvAYQ9BRJAswXBIgaltOsNSWkVbk/9mH6+womatrGOtKf3TJA3OyX1GY9s46uYc0Vilk4RYuI2vNv8aRvvYfl6Jr4INGTqktRszNc+p8rUuElJ4HVgUthz/UhclUxRwVWa9XkjS/eI/Qv0ACbNgt44QGCdkG8oXZlB4l3driuatqqhaQQ2OploCJH4HLPgJiL4lX/YYmM/cdzk3/ROBHHRdKnWWYs6uxNi+stz5kn+N/7tpu5QFpH2EtwTrmGWoDDqtD1VBQ7gzezFHOlB5ao4j2aaV95+5906uhSZTNPgOyou9e2jfOMloNqsBKxp37a25KE7tcHUFw7F6lfFkzt8sQvntL/tqpFLwM3exKj7U95/2+Sqqmoa0L4N2ogEo0J0NtQNXE=
