language: node_js
node_js: node
addons:
  chrome: stable
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:polymer:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:polymer:local || travis_terminate 1;
  fi
env:
  global:
  - SAUCE_USERNAME: Desire2Learn
  - secure: mb1k9/awo6pC2Y+yxc/X2meMlGY19OmAt+Prpgf5eJI0A/CmmsRihNwNlyAoffDnsh3BI4gZNr5viDpdjv3lQggWimkulb1eSNJzPuE+uNq580ki2Q5wpTSmiRGNloQWtbX7DzYJlhSOC/6kaprg62E3drOWe08apvinboYoc3ePHBQi4OzPRRy4VF0fBZSjeSw2DX4JeJ1TCUtrzHzBdVum+f2dmum06AttJbPmJU8OW0lLRR6T0a0ZMbSq1XlxHt1hw+hduzLzJQaRL1W6Awq1+W8jzjxBiG9/MLWY9AgfCcu30JwitYWgOsLMrcvAkU8wTCTGJNbXAkAHWt89W1tt0rUNSe86YM2DfKAGUmLxi3rYRT70Gs40FaSdqJMbkM0Lf3iDr90jw3Q54MJUaATUYZ8o46Waz+BSRmQsji1BEU1d+liHqy6kfH9yvHrLaQdSzFB56OKxapr1p5uiEKFu8bbY05AuDj4fnshrnjN9yywVOl3ml9f8KzP4SfcvqvOcWiNdYvGNanh1EGfv/ZZtosyXJCDeVzefNpXYTbB8nsdL5x4I+VROQV5eF8+9mMXuwISmvUB1VvkEL1XtAycqwaZno4UcTmJsnFiD5bEHZjrpATP4nR1tOJG9O5dKZxkeK4X2t20EhRHR/mOUC/t5wpkcPacol7l9uOoJ54w=
